services:
  db:
    restart: always
    image: "postgis/postgis:18-3.6"
    ports:
    - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    command: -p ${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql
      - ./postgis/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  import:
    # https://hub.docker.com/r/praszuk/osm-replication-osc-poly-filter
    # image: praszuk/osm-replication-osc-poly-filter:latest
    image: praszuk/osm-replication-osc-poly-filter:2.0-osm2pgsql-2.2.0
    env_file:
      - .env
    environment:
      PGPASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./data:/data
      - ./schemas:/schemas

volumes:
  db_data:
